name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  provider: ^6.1.2
  google_fonts: ^6.2.1
  logger: ^2.5.0
  file_picker: ^8.3.2
  path: ^1.9.0
  get_it: ^8.0.3
  dart_nats: ^0.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
